[tool.poetry]
name = "lsnms"
version = "0.3.2"
description = "Large Scale Non Maximum Suppression"
authors = ["Rémy Dubois <remydubois14@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remydubois/lsnms"
keywords = ["NMS", "Non Maximum Suppression", "Histology image", "Satellite images", "Object detection"]
classifiers=["Programming Language :: Python :: 3", "Topic :: Scientific/Engineering"]

[tool.poetry.dependencies]
python = ">=3.7"
numpy = ">=1.20.0"
numba = ">=0.54.1"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
tox = "3.24.4"
torch = "1.10.2"
torchvision = "0.11.3"
pillow = "9.3.0"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=30.3.0,<50",]
build-backend = "poetry.core.masonry.api"
